### ISSUE TITLE
Will adaptive-span have faster predictive speeds than gpt-2?

### ISSUE THREAD

**Issue by AnShengqiang** [facebookresearch/adaptive-span#10]
If adaptive-span and gpt-2 have the same model size and the same context length(e.g. 1024), will adaptive-span predict faster?

**Comment by tesatory** [comment]
I don't think they are directly comparable. But if you're asking adaptive-span VS fixed-span, then yes adaptive-span will be faster.

**Comment by AnShengqiang** [comment]
Thanks!
