### ISSUE TITLE
Compute attention span of individual attention heads

### ISSUE THREAD

**Issue by prajjwal1** [facebookresearch/adaptive-span#11]
I am working in model interpretability and wish to learn more about what each head is looking at and it's attention span (similar to the graphs from the paper). Could you please share what did you use to get the span of individual head ?

**Comment by tesatory** [comment]
You can get the average span like this 
https://github.com/facebookresearch/adaptive-span/blob/a8d90b8a8481ef1ae50a73b696c290aa88d34744/utils.py#L202
But if you want individual head spans, use this
`layer.attn.attn.adaptive_span._mask.current_val`
Note, it's in ratio (i.e. 0.5 means the span is half of the maximum possible length).

**Comment by prajjwal1** [comment]
Thank you for answering and sharing the code. 
1. In fig 5 of your paper, you show what the model is looking at with absolute attention span (not in ratio, I assume) ? How to do this ?
2. In fig 3, you show the change in span as data increases and the relation of #FLOPS with span limit. How can we track the span like the ones demonstrated above ?

**Comment by prajjwal1** [comment]
Thanks for your reply. I wanted to ask few more things:
- Do adaptive span change with time as the model sees more data ? Or is the span static ? In my experiments, they are not changing at all.
- Secondly, as long as the values in `current_val` lies between [0,1], adaptive span loss won't change right since you are using _clamp. So how much weight does a static loss carry ?
