### ISSUE TITLE
Accept a mask to remove padding in batch

### ISSUE THREAD

**Issue by bratao** [facebookresearch/adaptive-span#24]
@tesatory and team.

Thank you for releasing the Adaptive span transformer. For me is the best version of transformer so far!

On thing I noticed, comparing to another (great) transformer( https://github.com/idiap/fast-transformers), I noticed is that when  I set in the forward call the mask of padded items, the model converges much faster.

Is this something that could be on adaptive-span?

**Comment by tesatory** [comment]
Hi,

Sorry, I don't understand what "the mask of padded items" means here. Also, I don't really know how fast-transformers work, so I can't really say if it will work or not. Of course, you can try it out yourself if it's something simple to implement.
