### ISSUE TITLE
Why does the hyper-parameter --batch-sz affect the bpc during evaluation?

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/adaptive-span#26]
When I tune the hyper-parameter --batch-sz , I observe different results.

**Comment by zhaoguangxiang** [comment]
It seems that you split the whole sequence into   $batch_size  sub-sequences, they are treated as "independent" samples during training and evaluation.

**Comment by zhaoguangxiang** [comment]
On enwiki8, when I run the training for 8 iters with ngpu=8,bsz=64, I got 1.5bpc during evaluation. Then I stop the training and run the full evaluation, but I got 0.76 bpc with bsz=8 and 0.37 bpc with bsz=64

**Comment by tesatory** [comment]
It's what you said. The data is split into "batch-sz" parts and each part is processed independently. Then initial tokens in each part lacks context, so more parts means worse performance.
