### ISSUE TITLE
The way you preprocess data is different from that of Transformer-XL

### ISSUE THREAD

**Issue by yzh119** [facebookresearch/adaptive-span#5]
I noticed that you add a `<eos>` tokens at the end of each line:
https://github.com/facebookresearch/adaptive-span/blob/master/data.py#L34

But in Transformer-XL's code, they do not add`<eos>` for enwik8 and text8:
https://github.com/kimiyoung/transformer-xl/blob/master/pytorch/data_utils.py#L205

According to my experience, in enwik8 (sentence length is short), using `<eos>` would make the final bpc/bpb about 0.02 lower.
It's better if you use the same setting for fair comparison.

**Comment by ajoulin** [comment]
Hi,

enwik8 and text8 were introduced in the context of data compression, where every characters must be considered, including the end of line (`\n` replaced by `<eos>` in our code). 

Example of a previous dataloader used for character level language modeling on enwik8:
https://github.com/salesforce/awd-lstm-lm/blob/master/data.py

**Comment by yzh119** [comment]
Thanks for your justification, it's weird to see Transformer-XL not add eos for these two datasets, considering you use exactly the same `prep_enwik8.py` to preprocess data.

**Comment by ajoulin** [comment]
Note that `pre_enwik8.py` originally comes from the repository I linked in my previous message:

https://github.com/salesforce/awd-lstm-lm/tree/master/data/enwik8

**Comment by yzh119** [comment]
Right, I mean though using the same script, the way Transformer-XL load data is still different from yours and awd-lstm. 
It seems including eos is the right way in the context of compression.

**Comment by lucaslingle** [comment]
In case anyone else was wondering about this: 

The preprocessing script ```prep_enwik8.py``` used by Transformer-XL keeps newlines intact when it writes the characters back out to a separate file. Then, when ```vocab.encode_file``` is used, the code [here](https://github.com/kimiyoung/transformer-xl/blob/master/pytorch/utils/vocabulary.py#L98) reads in the preprocessed data line-by-line, keeping the ending ```\n``` appended to each line. Tokenization subsequently treats ```\n``` as a separate token. 

Thus, ```\n``` tokens are not dropped by the Transformer-XL preprocessing, and no ```<eos>``` character is needed.
