### ISSUE TITLE
Using mask can reduce FLOPs?

### ISSUE THREAD

**Issue by amxineohp** [facebookresearch/adaptive-span#6]
Hi,
Good Paper.
From the source code your idea is implemented by mask(AdaptiveMask) which means  there will be no FLOPs saving right?

**Comment by tesatory** [comment]
FLOPS are reduced by this line where we cut out parts where the mask is zero https://github.com/facebookresearch/adaptive-span/blob/master/models.py#L67

**Comment by amxineohp** [comment]
Got it, your implementation is based on history(transformer-xl like)
Thanks
