### ISSUE TITLE
Question: How to reduce the memory in this project

### ISSUE THREAD

**Issue by yangyaofei** [facebookresearch/adaptive-span#7]
Hi, I read your paper ,it's great. I'm very interesting about how to reduce the memory in the real project.

I guess the memory things are:
 in https://github.com/facebookresearch/adaptive-span/blob/d882404be50f488d85683b8b925f0c6aef33e9f3/adaptive_span.py#L127

But I just see you cut the `key_pe` and It's just reduce a little memory and wouldn't help for reduce the Q K things I think.

So. can you explain How to reduce the memory in the code? 

thanks

**Comment by dalpo814** [comment]
I think that unskewing attention probs matrix (modeling.py line 73) can reduce the memory a lot.

**Comment by yangyaofei** [comment]
I will look that again , thank you

dalpo814 <notifications@github.com> 于 2019年7月16日周二 16:55写道：

**Comment by tesatory** [comment]
K is being cut too here https://github.com/facebookresearch/adaptive-span/blob/d882404be50f488d85683b8b925f0c6aef33e9f3/adaptive_span.py#L123

**Comment by yangyaofei** [comment]
@tesatory sorry, I can't get it . that's code will pad the key to zero but not reduce the memory.

**Comment by tesatory** [comment]
Sorry wrong line. It is cut here https://github.com/facebookresearch/adaptive-span/blob/d882404be50f488d85683b8b925f0c6aef33e9f3/adaptive_span.py#L118

**Comment by yangyaofei** [comment]
@tesatory thank you to reply, I still have some confuse.  
It's something like the 0:trim_len_catch was computed, in this time it just use the catch that was computed previous .

I want to know is : 

in your paper, you said you use a sub-network to help attention to pick a range to compute the attention. It will reduce memory, because we can cut the unnecessary part. I can't find that part,because for every element in attention, the range is different. for 5th and length is 30 is from 0 to 35 like that. I have some idea same as that, but I can't find a proper way to do that. 

I read your paper, I think your project can help. 
thank you

**Comment by yangyaofei** [comment]
@tesatory oh, sorry, I realize your paper is not what I thought. It's reduce the memory in generation. Thanks
