### ISSUE TITLE
why not compare other local attention methods？

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/adaptive-span#9]
e.g. Modeling Localness for Self-Attention Networks 
Convolutional self attention

**Comment by tesatory** [comment]
We are not sure if the method from "Modeling Localness for Self-Attention Networks" would scale to attentions spans as long as 8,000. In that paper, the longest learned context was about 50 I think, so it's orders of magnitude smaller than our longest attention span.

**Comment by zhaoguangxiang** [comment]
I am happy to hear from you.  I am curious about the reason of this difference.
